spring.application.name=ms_autenticacion_usuario
server.port=8097

spring.datasource.url=jdbc:mysql://localhost:3306/ms_autenticacion_usuario
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false

eureka.client.eureka-server-http-client-name=RestClient

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info

management.info.env.enabled=true

info.app.name=MS Peluqueria: Autenticacion de Usuario
info.app.description= Modulo para el manejo de autenticaciones de usuarios.
info.app.version=1.0.0